version: '3'
services:
  app:
    environment:
      - TAG
    image: "employees:${TAG}"
    env_file:
        - ../.env
    ports:
      - "4000:3000"
    volumes:
      - "$PWD:/usr/src/app"
      - "/usr/src/app/node_modules"
    networks:
      - proxy
    deploy:
      mode: replicated
      replicas: 2
      resources:
        limits:
          memory: 128M
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api_notes.rule=Host(`www.employees.tech`)"
      - "traefik.http.routers.api_notes.tls=true"
      - "traefik.http.routers.api_notes.tls.certresolver=le"
      - "traefik.http.services.api_notes.loadbalancer.server.port=3000"
networks:
  proxy:
    external: true
